# Generated by Django 4.1.2 on 2022-10-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=80)),
                ('baseprice', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('finalprice', models.FloatField()),
                ('stock', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_api.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_api.category')),
            ],
        ),
    ]
